### PR TITLE
add selenium_bot.py, add driver for MacOS, Windows and Linux os

### PR DESCRIPTION
**Pull request by sazzad03**
selenium class added.

### CODE REVIEW

**Comment by G-Sivley** [comment]
@sazzad03 Thank you for your help. Your efforts are much appreciated. Please let me know if there are any other edits that can be made to the app, or if there is something else you would like to work on!

**Comment by sazzad03** [comment]
Hello @G-Sivley, Thank you for your positive feedback.. 😄
I think this project is interesting and I am planning to contribute as much as I can. 

Thank you.

**Comment by sazzad03** [comment]
I also want to request you to check the selenium_bot.py in windows and linux and if it gives any error please let me know.
also feel free to assign me any issues.

**Comment by G-Sivley** [comment]
@sazzad03 Would you be interested in working on issue #12

**Comment by sazzad03** [comment]
yes, i will work on the issue #12 :)

**Pull request merged**
